# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: hthomas <hthomas@student.42.fr>            +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/04/21 16:36:28 by hthomas           #+#    #+#              #
#    Updated: 2020/04/24 12:34:52 by hthomas          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME =		Phonebook

CC =		clang++
CFLAGS =	-Wall -Werror -Wextra

SRCS =		$(NAME).cpp


all: $(NAME)

$(NAME): $(SRCS)
	$(CC) $(CFLAGS) $(SRCS) -o $(NAME)