# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: hugothms <hugothms@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/04/25 16:00:55 by hthomas           #+#    #+#              #
#    Updated: 2020/05/03 15:49:40 by hugothms         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME =		a.out

CC =		clang++
CFLAGS =	-Wall -Werror -Wextra

SRCS =		Brain.cpp	\
			Human.cpp	\
			main.cpp

all: $(NAME)

$(NAME): $(SRCS)
	$(CC) $(SRCS) -o $(NAME)